# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'calculator.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(431, 372)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.one = QtWidgets.QPushButton(self.centralwidget)
        self.one.setGeometry(QtCore.QRect(9, 80, 71, 61))
        font = QtGui.QFont()
        font.setFamily("나눔스퀘어라운드 Regular")
        font.setPointSize(22)
        self.one.setFont(font)
        self.one.setObjectName("one")
        self.two = QtWidgets.QPushButton(self.centralwidget)
        self.two.setGeometry(QtCore.QRect(89, 80, 71, 61))
        font = QtGui.QFont()
        font.setFamily("나눔스퀘어라운드 Regular")
        font.setPointSize(22)
        self.two.setFont(font)
        self.two.setObjectName("two")
        self.three = QtWidgets.QPushButton(self.centralwidget)
        self.three.setGeometry(QtCore.QRect(169, 80, 71, 61))
        font = QtGui.QFont()
        font.setFamily("나눔스퀘어라운드 Regular")
        font.setPointSize(22)
        self.three.setFont(font)
        self.three.setObjectName("three")
        self.five = QtWidgets.QPushButton(self.centralwidget)
        self.five.setGeometry(QtCore.QRect(89, 150, 71, 61))
        font = QtGui.QFont()
        font.setFamily("나눔스퀘어라운드 Regular")
        font.setPointSize(22)
        self.five.setFont(font)
        self.five.setObjectName("five")
        self.four = QtWidgets.QPushButton(self.centralwidget)
        self.four.setGeometry(QtCore.QRect(9, 150, 71, 61))
        font = QtGui.QFont()
        font.setFamily("나눔스퀘어라운드 Regular")
        font.setPointSize(22)
        self.four.setFont(font)
        self.four.setObjectName("four")
        self.six = QtWidgets.QPushButton(self.centralwidget)
        self.six.setGeometry(QtCore.QRect(169, 150, 71, 61))
        font = QtGui.QFont()
        font.setFamily("나눔스퀘어라운드 Regular")
        font.setPointSize(22)
        self.six.setFont(font)
        self.six.setObjectName("six")
        self.seven = QtWidgets.QPushButton(self.centralwidget)
        self.seven.setGeometry(QtCore.QRect(9, 220, 71, 61))
        font = QtGui.QFont()
        font.setFamily("나눔스퀘어라운드 Regular")
        font.setPointSize(22)
        self.seven.setFont(font)
        self.seven.setObjectName("seven")
        self.eight = QtWidgets.QPushButton(self.centralwidget)
        self.eight.setGeometry(QtCore.QRect(89, 220, 71, 61))
        font = QtGui.QFont()
        font.setFamily("나눔스퀘어라운드 Regular")
        font.setPointSize(22)
        self.eight.setFont(font)
        self.eight.setObjectName("eight")
        self.nine = QtWidgets.QPushButton(self.centralwidget)
        self.nine.setGeometry(QtCore.QRect(169, 220, 71, 61))
        font = QtGui.QFont()
        font.setFamily("나눔스퀘어라운드 Regular")
        font.setPointSize(22)
        self.nine.setFont(font)
        self.nine.setObjectName("nine")
        self.zero = QtWidgets.QPushButton(self.centralwidget)
        self.zero.setGeometry(QtCore.QRect(89, 289, 71, 61))
        font = QtGui.QFont()
        font.setFamily("나눔스퀘어라운드 Regular")
        font.setPointSize(22)
        self.zero.setFont(font)
        self.zero.setObjectName("zero")
        self.plus = QtWidgets.QPushButton(self.centralwidget)
        self.plus.setGeometry(QtCore.QRect(259, 80, 71, 61))
        font = QtGui.QFont()
        font.setFamily("나눔스퀘어라운드 Regular")
        font.setPointSize(22)
        self.plus.setFont(font)
        self.plus.setObjectName("plus")
        self.minus = QtWidgets.QPushButton(self.centralwidget)
        self.minus.setGeometry(QtCore.QRect(339, 80, 71, 61))
        font = QtGui.QFont()
        font.setFamily("나눔스퀘어라운드 Regular")
        font.setPointSize(22)
        self.minus.setFont(font)
        self.minus.setObjectName("minus")
        self.multiply = QtWidgets.QPushButton(self.centralwidget)
        self.multiply.setGeometry(QtCore.QRect(259, 150, 71, 61))
        font = QtGui.QFont()
        font.setFamily("나눔스퀘어라운드 Regular")
        font.setPointSize(22)
        self.multiply.setFont(font)
        self.multiply.setObjectName("multiply")
        self.equal = QtWidgets.QPushButton(self.centralwidget)
        self.equal.setGeometry(QtCore.QRect(260, 221, 71, 61))
        font = QtGui.QFont()
        font.setFamily("나눔스퀘어라운드 Regular")
        font.setPointSize(22)
        self.equal.setFont(font)
        self.equal.setObjectName("equal")
        self.divide = QtWidgets.QPushButton(self.centralwidget)
        self.divide.setGeometry(QtCore.QRect(339, 150, 71, 61))
        font = QtGui.QFont()
        font.setFamily("나눔스퀘어라운드 Regular")
        font.setPointSize(22)
        self.divide.setFont(font)
        self.divide.setObjectName("divide")
        self.clear = QtWidgets.QPushButton(self.centralwidget)
        self.clear.setGeometry(QtCore.QRect(339, 220, 71, 61))
        font = QtGui.QFont()
        font.setFamily("나눔스퀘어라운드 Regular")
        font.setPointSize(22)
        self.clear.setFont(font)
        self.clear.setObjectName("clear")
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(10, 10, 401, 61))
        self.textBrowser.setObjectName("textBrowser")
        self.left_p = QtWidgets.QPushButton(self.centralwidget)
        self.left_p.setGeometry(QtCore.QRect(219, 289, 71, 61))
        font = QtGui.QFont()
        font.setFamily("나눔스퀘어라운드 Regular")
        font.setPointSize(22)
        self.left_p.setFont(font)
        self.left_p.setObjectName("left_p")
        self.right_p = QtWidgets.QPushButton(self.centralwidget)
        self.right_p.setGeometry(QtCore.QRect(299, 289, 71, 61))
        font = QtGui.QFont()
        font.setFamily("나눔스퀘어라운드 Regular")
        font.setPointSize(22)
        self.right_p.setFont(font)
        self.right_p.setObjectName("right_p")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.one.clicked.connect(self.c_1)
        self.two.clicked.connect(self.c_2)
        self.three.clicked.connect(self.c_3)
        self.four.clicked.connect(self.c_4)
        self.five.clicked.connect(self.c_5)
        self.six.clicked.connect(self.c_6)
        self.seven.clicked.connect(self.c_7)
        self.eight.clicked.connect(self.c_8)
        self.nine.clicked.connect(self.c_9)
        self.zero.clicked.connect(self.c_0)
        self.plus.clicked.connect(self.c_plus)
        self.multiply.clicked.connect(self.c_mul)
        self.equal.clicked.connect(self.c_eql)
        self.minus.clicked.connect(self.c_minus)
        self.divide.clicked.connect(self.c_div)
        self.clear.clicked.connect(self.c_clr)
        self.left_p.clicked.connect(self.c_lp)
        self.right_p.clicked.connect(self.c_rp)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)


    def c_1(self):
        self.textBrowser.setPlainText(self.textBrowser.toPlainText()+str(1))
    def c_2(self):
        self.textBrowser.setPlainText(self.textBrowser.toPlainText()+str(2))
    def c_3(self):
        self.textBrowser.setPlainText(self.textBrowser.toPlainText()+str(3))
    def c_4(self):
        self.textBrowser.setPlainText(self.textBrowser.toPlainText()+str(4))
    def c_5(self):
        self.textBrowser.setPlainText(self.textBrowser.toPlainText()+str(5))
    def c_6(self):
        self.textBrowser.setPlainText(self.textBrowser.toPlainText()+str(6))
    def c_7(self):
        self.textBrowser.setPlainText(self.textBrowser.toPlainText()+str(7))
    def c_8(self):
        self.textBrowser.setPlainText(self.textBrowser.toPlainText()+str(8))
    def c_9(self):
        self.textBrowser.setPlainText(self.textBrowser.toPlainText()+str(9))
    def c_0(self):
        self.textBrowser.setPlainText(self.textBrowser.toPlainText()+str(0))
    def c_plus(self):
        self.textBrowser.setPlainText(self.textBrowser.toPlainText()+'+')
    def c_minus(self):
        self.textBrowser.setPlainText(self.textBrowser.toPlainText()+'-')
    def c_mul(self):
        self.textBrowser.setPlainText(self.textBrowser.toPlainText()+'x')
    def c_div(self):
        self.textBrowser.setPlainText(self.textBrowser.toPlainText()+'/')

    def c_lp(self):
        self.textBrowser.setPlainText(self.textBrowser.toPlainText()+'(')
    def c_rp(self):
        self.textBrowser.setPlainText(self.textBrowser.toPlainText()+')')    
    def c_clr(self):
        self.textBrowser.clear()
    def c_eql(self):            
        self.textBrowser.setPlainText(str(eval(self.textBrowser.toPlainText().replace('x','*'))))
            
        

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.one.setText(_translate("MainWindow", "1"))
        self.two.setText(_translate("MainWindow", " 2"))
        self.three.setText(_translate("MainWindow", "3"))
        self.five.setText(_translate("MainWindow", "5"))
        self.four.setText(_translate("MainWindow", "4"))
        self.six.setText(_translate("MainWindow", "6"))
        self.seven.setText(_translate("MainWindow", "7"))
        self.eight.setText(_translate("MainWindow", "8"))
        self.nine.setText(_translate("MainWindow", "9"))
        self.zero.setText(_translate("MainWindow", "0"))
        self.plus.setText(_translate("MainWindow", "+"))
        self.minus.setText(_translate("MainWindow", "-"))
        self.multiply.setText(_translate("MainWindow", "x"))
        self.equal.setText(_translate("MainWindow", "="))
        self.divide.setText(_translate("MainWindow", "/"))
        self.clear.setText(_translate("MainWindow", "CLR"))
        self.left_p.setText(_translate("MainWindow", "("))
        self.right_p.setText(_translate("MainWindow", ")"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

